
version: 2
jobs:
  checkout_code:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
        name: Install dependencies
        command: |
          pwd
          ls

  python_dependencies:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - run:
          name: Install dependencies
          command: |
            pwd
            ls
  static_anylysis:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - run:
          name: Install dependencies
          command: |
            pwd
            ls
  unit_tests:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - run:
          name: Install dependencies
          command: |
            pwd
            ls
  deploy_dev:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - run:
          name: Install dependencies
          command: |
            pwd
            ls

workflows:
  version: 2
  simplezat-pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - static_anylysis:
          requires:
            - python_dependencies
      - unit_tests:
          requires:
            - python_dependencies
      - deploy_dev:
          requires:
            - unit_tests



