
version: 2
jobs:
  checkout_code:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  python_dependencies:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: |
            pip3 install pipenv
            pipenv install --dev

  static_anylysis:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run static analysis
          command: |
            pipenv install --dev
            pipenv run flake8

  unit_tests:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unittest
          command: |
            pipenv install --dev
            cd simplezat && pipenv run python manage.py test

  deploy_dev:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Buid Stabel Images
          command: |
            docker build -t popsoften/simplezat:stable -f Dockerfile.dev .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push popsoften/simplezat:stable
      - add_ssh_keys:
          fingerprints:
            - "c5:82:08:8d:9f:56:a7:26:68:1b:70:4d:07:82:3b:6f"
      - run:
          name: Deploy to Dev
          command: |
            cd deployment
            pipenv install
            pipenv run ansible-playbook -i hosts playbooks/dev.yml --extra-vars "project_root=~/simplezat/"

workflows:
  version: 2
  simplezat-pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - static_anylysis:
          requires:
            - python_dependencies
      - unit_tests:
          requires:
            - python_dependencies
      - deploy_dev:
          requires:
            - unit_tests



