
version: 2
jobs:
  checkout_code:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  python_dependencies:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: |
            pip3 install pipenv
            pipenv install --dev

  static_anylysis:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run static analysis
          command: |
            pipenv install --dev
            pipenv run flake8

  unit_tests:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unittest
          command: |
            pipenv install --dev
            cd simplezat && pipenv run python manage.py test

  deploy_dev:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Buid Stable Images
          command: |
            docker build -t popsoften/simplezat:stable -f Dockerfile.dev .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push popsoften/simplezat:stable
      - add_ssh_keys:
          fingerprints:
            - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"
      - run:
          name: Deploy to Dev
          command: |
            cd deployment
            ssh-keyscan -H 35.237.130.8 >> ~/.ssh/known_hosts
            pipenv install
            pipenv run ansible-playbook -i hosts playbooks/dev.yml --extra-vars "project_root=~/simplezat/"

  deploy_prod:
    working_directory: ~/simplezat
    docker:
      - image: circleci/python:3.7.1
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Buid Live Images
          command: |
            docker build -t popsoften/simplezat:live -f Dockerfile.production .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push popsoften/simplezat:live
      - add_ssh_keys:
          fingerprints:
            - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"
      - run:
          name: Deploy to Production
          command: |
            cd deployment
            ssh-keyscan -H 104.196.96.7 >> ~/.ssh/known_hosts
            pipenv install
            pipenv run ansible-playbook -i hosts playbooks/prod.yml --extra-vars "project_root=~/simplezat/"

workflows:
  version: 2
  simplezat-pipeline:
    jobs:
      - checkout_code
      - python_dependencies:
          requires:
            - checkout_code
      - static_anylysis:
          requires:
            - python_dependencies
      - unit_tests:
          requires:
            - python_dependencies
      - deploy_dev:
          requires:
            - unit_tests
      - wait_for_approval:
          type: approval
          requires:
            - deploy_dev
      - deploy_production:
          requires:
            - wait_for_approval






